[build]
builder = "nixpacks"
buildCommand = "cd backend ; npm install ; npm run dev"

[deploy]
startCommand = "cd backend ; npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
